repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: type-check
        name: TypeScript Type Check
        entry: npm run type-check
        language: system
        files: \.(ts)$
        require_serial: true

      - id: test
        name: Run Tests
        entry: npm test -- --passWithNoTests
        language: system
        types: [typescript]
        require_serial: true
        env:
          NODE_ENV: 'test'

      - id: security-check
        name: Security Audit
        entry: npm audit --audit-level=high
        language: system
        require_serial: true
        pass_filenames: false

      - id: admin-permissions-check
        name: Admin Permissions Validation
        entry: npm run validate:permissions
        language: system
        types: [typescript]
        require_serial: true